/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/pricing`; params?: Router.UnknownInputParams; } | { pathname: `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/billing`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/orders`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/products`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/profile`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/share`; params?: Router.UnknownInputParams; } | { pathname: `/shop/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/shop/confirmation`; params?: Router.UnknownInputParams; } | { pathname: `/shop/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/pricing`; params?: Router.UnknownOutputParams; } | { pathname: `/reset-password`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/billing`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/products`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/share`; params?: Router.UnknownOutputParams; } | { pathname: `/shop/checkout`; params?: Router.UnknownOutputParams; } | { pathname: `/shop/confirmation`; params?: Router.UnknownOutputParams; } | { pathname: `/shop/[slug]`, params: Router.UnknownOutputParams & { slug: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/pricing${`?${string}` | `#${string}` | ''}` | `/reset-password${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/dashboard/billing${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard/orders${`?${string}` | `#${string}` | ''}` | `/dashboard/products${`?${string}` | `#${string}` | ''}` | `/dashboard/profile${`?${string}` | `#${string}` | ''}` | `/dashboard/share${`?${string}` | `#${string}` | ''}` | `/shop/checkout${`?${string}` | `#${string}` | ''}` | `/shop/confirmation${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/pricing`; params?: Router.UnknownInputParams; } | { pathname: `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/billing`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/orders`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/products`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/profile`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/share`; params?: Router.UnknownInputParams; } | { pathname: `/shop/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/shop/confirmation`; params?: Router.UnknownInputParams; } | `/shop/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/shop/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
    }
  }
}
